export const FETCH_THONGTIN_REQUEST = "thongtin/FETCH_THONGTIN_REQUEST";
export const FETCH_THONGTIN_SUCCESS = "thongtin/FETCH_THONGTIN_SUCCESS";
export const FETCH_THONGTIN_FAILED = "thongtin/FETCH_THONGTIN_FAILED";


export const DELETE_THONGTIN_REQUEST = "thongtin/DELETE_THONGTIN_REQUEST";
export const DELETE_THONGTIN_SUCCESS = "thongtin/DELETE_THONGTIN_SUCCESS";
export const DELETE_THONGTIN_FAILED = "thongtin/DELETE_THONGTIN_FAILED";



export const EDIT_THONGTIN_REQUEST = "thongtin/EDIT_THONGTIN_REQUEST";
export const EDIT_THONGTIN_SUCCESS = "thongtin/EDIT_THONGTIN_SUCCESS";
export const EDIT_THONGTIN_FAILED = "thongtin/EDIT_THONGTIN_FAILED";